//
// ApiResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Describes the result of uploading an image resource */

public struct ApiResponse: Codable {

    public var code: Int?
    public var type: String?
    public var message: String?

    public init(code: Int?, type: String?, message: String?) {
        self.code = code
        self.type = type
        self.message = message
    }

}

extension ApiResponse: Fakeable {

    static var defaultFakeValue: ApiResponse { 
        return ApiResponse.makeFake()
    }
  
    static func makeFake(
                    code: Int? = .fake(), 
                    type: String? = .fake(), 
                    message: String? = .fake()
                    ) -> ApiResponse { 
     return ApiResponse(code: code,
            type: type,
            message: message)
    }
}

