//
// Body1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Body1: Codable {

    /** Additional data to pass to server */
    public var additionalMetadata: String?
    /** file to upload */
    public var file: Data?

    public init(additionalMetadata: String?, file: Data?) {
        self.additionalMetadata = additionalMetadata
        self.file = file
    }

}

extension Body1: Fakeable {

    static var defaultFakeValue: Body1 { 
        return Body1.makeFake()
    }
  
    static func makeFake(
                    additionalMetadata: String? = .fake(), 
                    file: Data? = .fake()
                    ) -> Body1 { 
     return Body1(additionalMetadata: additionalMetadata,
            file: file)
    }
}

