//
// Body.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Body: Codable {

    /** Updated name of the pet */
    public var name: String?
    /** Updated status of the pet */
    public var status: String?

    public init(name: String?, status: String?) {
        self.name = name
        self.status = status
    }

}

extension Body: Fakeable {

    static var defaultFakeValue: Body { 
        return Body.makeFake()
    }
  
    static func makeFake(
                    name: String? = .fake(), 
                    status: String? = .fake()
                    ) -> Body { 
     return Body(name: name,
            status: status)
    }
}

