//
// Currency.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** some description  */

public struct Currency: Codable {



}

extension Currency: Fakeable {

    static var defaultFakeValue: Currency { 
        return Currency.makeFake()
    }
  
    static func makeFake(
                    ) -> Currency { 
     return Currency()
    }
}

