//
// Order.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An order for a pets from the pet store */

public struct Order: Codable {

    public enum Status: String, Codable { 
        case placed = "placed"
        case approved = "approved"
        case delivered = "delivered"
    }
    public var _id: Int64?
    public var petId: Int64?
    public var quantity: Int?
    public var shipDate: Date?
    /** Order Status */
    public var status: Status?
    public var complete: Bool?

    public init(_id: Int64?, petId: Int64?, quantity: Int?, shipDate: Date?, status: Status?, complete: Bool?) {
        self._id = _id
        self.petId = petId
        self.quantity = quantity
        self.shipDate = shipDate
        self.status = status
        self.complete = complete
    }
    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case petId
        case quantity
        case shipDate
        case status
        case complete
    }

}

extension Order: Fakeable {

    static var defaultFakeValue: Order { 
        return Order.makeFake()
    }
  
    static func makeFake(
                    _id: Int64? = .fake(), 
                    petId: Int64? = .fake(), 
                    quantity: Int? = .fake(), 
                    shipDate: Date? = .fake(), 
                    status: Status? = .fake(), 
                    complete: Bool? = .fake()
                    ) -> Order { 
     return Order(_id: _id,
            petId: petId,
            quantity: quantity,
            shipDate: shipDate,
            status: status,
            complete: complete)
    }
}

extension Order.Status: Fakeable { 
    static var defaultFakeValue: Order.Status {
    return .placed
    }
}  
