//
// Pet.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A pet for sale in the pet store */

public struct Pet: Codable {

    public enum Status: String, Codable { 
        case available = "available"
        case pending = "pending"
        case sold = "sold"
    }
    public var _id: Int64?
    public var category: Category?
    public var name: String
    public var photoUrls: [String]
    public var tags: [Tag]?
    /** pet status in the store */
    public var status: Status?

    public init(_id: Int64?, category: Category?, name: String, photoUrls: [String], tags: [Tag]?, status: Status?) {
        self._id = _id
        self.category = category
        self.name = name
        self.photoUrls = photoUrls
        self.tags = tags
        self.status = status
    }
    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case category
        case name
        case photoUrls
        case tags
        case status
    }

}

extension Pet: Fakeable {

    static var defaultFakeValue: Pet { 
        return Pet.makeFake()
    }
  
    static func makeFake(
                    _id: Int64? = .fake(), 
                    category: Category? = .fake(), 
                    name: String = .fake(), 
                    photoUrls: [String] = .fake(), 
                    tags: [Tag]? = .fake(), 
                    status: Status? = .fake()
                    ) -> Pet { 
     return Pet(_id: _id,
            category: category,
            name: name,
            photoUrls: photoUrls,
            tags: tags,
            status: status)
    }
}

extension Pet.Status: Fakeable { 
    static var defaultFakeValue: Pet.Status {
    return .available
    }
}  
