//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A User who is purchasing from the pet store */

public struct User: Codable {

    public var _id: Int64?
    public var username: String?
    public var firstName: String?
    public var lastName: String?
    public var email: String?
    public var password: String?
    public var phone: String?
    /** User Status */
    public var userStatus: Int?

    public init(_id: Int64?, username: String?, firstName: String?, lastName: String?, email: String?, password: String?, phone: String?, userStatus: Int?) {
        self._id = _id
        self.username = username
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
        self.password = password
        self.phone = phone
        self.userStatus = userStatus
    }
    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case username
        case firstName
        case lastName
        case email
        case password
        case phone
        case userStatus
    }

}

extension User: Fakeable {

    static var defaultFakeValue: User { 
        return User.makeFake()
    }
  
    static func makeFake(
                    _id: Int64? = .fake(), 
                    username: String? = .fake(), 
                    firstName: String? = .fake(), 
                    lastName: String? = .fake(), 
                    email: String? = .fake(), 
                    password: String? = .fake(), 
                    phone: String? = .fake(), 
                    userStatus: Int? = .fake()
                    ) -> User { 
     return User(_id: _id,
            username: username,
            firstName: firstName,
            lastName: lastName,
            email: email,
            password: password,
            phone: phone,
            userStatus: userStatus)
    }
}

